---
collections:
  - name: community.docker
  - name: community.postgresql
  - name: https://github.com/hyphacoop/ansible-common.git
    type: git
    version: e862f2c7c4e7b929e3216fa359e954bed9ec98e1
  - name: https://github.com/lvrfrc87/git-acp-ansible.git
    type: git
    version: 8bfa71dd63dde0e7a4d99174fec65ddc23427434
roles:
  - src: geerlingguy.docker
  - src: geerlingguy.nodejs
