---
collections:
  - name: community.docker
  - name: community.postgresql
  - name: https://github.com/hyphacoop/ansible-common.git
    type: git
    version: 28694575c335393289d7cbeafc89aebeaca5d76e
roles:
  - src: geerlingguy.docker
  - src: geerlingguy.nodejs
