---
- name: configure systemd service for cascadiad
  when: not use_cosmovisor
  template:
    src: cascadiad.service.j2
    dest: "/etc/systemd/system/{{cascadiad_service_name}}.service"

- name: configure systemd service for cosmovisor
  when: use_cosmovisor
  template:
    src: cosmovisor.service.j2
    dest: "/etc/systemd/system/{{cosmovisor_service_name}}.service"

- name: Restart journalctl so that the logs may flow
  systemd:
    state: restarted
    name: systemd-journald

- name: Enable cascadiad systemd service
  when: not use_cosmovisor
  systemd:
    daemon_reload: true
    state: stopped
    enabled: true
    name: "{{cascadiad_service_name}}"

- name: Start cascadiad systemd service
  when: (not use_cosmovisor) and (not reboot | default(false) | bool)
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{cascadiad_service_name}}"
  tags:
    - cascadiad_start
    - cascadiad_restart

- name: Enable cosmovisor systemd service
  when: use_cosmovisor
  systemd:
    daemon_reload: true
    state: stopped
    enabled: true
    name: "{{cosmovisor_service_name}}"

- name: Start cosmovisor systemd service
  when: (use_cosmovisor) and (not reboot | default(false) | bool)
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{cosmovisor_service_name}}"
  tags:
    - cascadiad_start
    - cascadiad_restart
