---
- name: Configure Hermes
  template:
    src: config.toml.j2
    dest: /home/{{ hermes_user }}/.hermes/config.toml
  become_user: "{{ hermes_user }}"

- name: Get chain IDs
  set_fact:
    chain_ids: "{{ hermes_chains.keys() | list }}"

- name: Upload key file from first chain
  copy:
    src: '{{ hermes_chains[chain_ids[0]].hermes_relayer_key }}'
    dest: '/home/{{ hermes_user }}/.hermes/{{ chain_ids[0] }}-relayer.json'
    owner: '{{hermes_user}}'
    group: '{{hermes_group}}'
  when: hermes_relayer_keys is defined

- name: Upload key file from second chain
  copy:
    src: '{{ hermes_chains[chain_ids[1]].hermes_relayer_key }}'
    dest: '/home/{{ hermes_user }}/.hermes/{{ chain_ids[1] }}-relayer.json'
    owner: '{{hermes_user}}'
    group: '{{hermes_group}}'
  when: hermes_relayer_keys

- name: Add relayer keys
  shell: |
    hermes keys add --key-file /home/{{ hermes_user }}/.hermes/{{ chain_ids[0] }}-relayer.json --chain {{ chain_ids[0] }} --overwrite
    hermes keys add --key-file /home/{{ hermes_user }}/.hermes/{{ chain_ids[1] }}-relayer.json --chain {{ chain_ids[1] }} --overwrite
  environment:
    PATH: "/home/{{hermes_user}}/bin:{{ ansible_env.PATH }}"
  become_user: hermes
  when: hermes_relayer_keys

- name: Upload mnemonic from first chain
  copy:
    src: '{{ hermes_chains[chain_ids[0]].hermes_relayer_mnemonic }}'
    dest: '/home/{{ hermes_user }}/.hermes/{{ chain_ids[0] }}-relayer.txt'
    owner: '{{hermes_user}}'
    group: '{{hermes_group}}'
  when: hermes_relayer_mnemonics

- name: Upload mnemonic file from second chain
  copy:
    src: '{{ hermes_chains[chain_ids[1]].hermes_relayer_mnemonic }}'
    dest: '/home/{{ hermes_user }}/.hermes/{{ chain_ids[1] }}-relayer.txt'
    owner: '{{hermes_user}}'
    group: '{{hermes_group}}'
  when: hermes_relayer_mnemonics

- name: Add relayer keys from mnemonics
  shell: |
    hermes keys add --mnemonic-file /home/{{ hermes_user }}/.hermes/{{ chain_ids[0] }}-relayer.txt --chain {{ chain_ids[0] }} --overwrite
    hermes keys add --mnemonic-file /home/{{ hermes_user }}/.hermes/{{ chain_ids[1] }}-relayer.txt --chain {{ chain_ids[1] }} --overwrite
  environment:
    PATH: "/home/{{hermes_user}}/bin:{{ ansible_env.PATH }}"
  become_user: hermes
  when: hermes_relayer_mnemonics

- name: Create connection
  shell: |
    hermes create connection --a-chain {{ chain_ids[0] }} --b-chain {{ chain_ids[1] }}
  environment:
    PATH: "/home/{{hermes_user}}/bin:{{ ansible_env.PATH }}"
  become_user: hermes

- name: Create channel
  shell: |
    hermes create channel --a-chain {{ chain_ids[0] }} \
    --a-port {{ hermes_chains[chain_ids[0]].hermes_port_name}} \
    --b-port {{ hermes_chains[chain_ids[1]].hermes_port_name}} \
    --order {{ hermes_order }} --a-connection connection-0
  environment:
    PATH: "/home/{{hermes_user}}/bin:{{ ansible_env.PATH }}"
  become_user: hermes
