---
- include_role:
    name: common

- name: Create hermes user
  user:
    name: "{{ hermes_user }}"
    group: "{{ hermes_group }}"
    shell: /bin/bash
    append: no

- name: chown hermes home directory
  file:
    path: /home/{{ hermes_user }}
    state: directory
    owner: "{{ hermes_user }}"
    group: "{{ hermes_group }}"
    mode: '0755'


- name: Create ~/.hermes/bin directory
  file:
    path: /home/{{ hermes_user }}/.hermes/bin
    state: directory
    owner: "{{ hermes_user }}"
    group: "{{ hermes_group }}"
    mode: '0755'

- name: Create ~/bin directory
  file:
    path: /home/{{ hermes_user }}/bin
    state: directory
    owner: "{{ hermes_user }}"
    group: "{{ hermes_group }}"
    mode: '0755'

- name: Get latest gaiad version
  uri:
    url: https://api.github.com/repos/cosmos/gaia/releases/latest
    return_content: true
  register: json_reponse

- name: Download gaiad
  get_url:
    url: https://github.com/cosmos/gaia/releases/download/{{ json_reponse.json.tag_name }}/gaiad-{{ json_reponse.json.tag_name }}-linux-amd64
    dest: /home/{{ hermes_user }}/bin/gaiad
    mode: 0755
  become_user: "{{ hermes_user }}"

- name: Get latest hermes version
  uri:
    url: https://api.github.com/repos/informalsystems/ibc-rs/releases/latest
    return_content: true
  register: json_reponse

- name: Download and Extract hermes
  unarchive:
    src: https://github.com/informalsystems/ibc-rs/releases/download/{{ json_reponse.json.tag_name }}/hermes-{{ json_reponse.json.tag_name }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /home/{{ hermes_user }}/.hermes/bin/
    remote_src: yes
  become_user: "{{ hermes_user }}"

- name: ln -s /home/{{ hermes_user }}/.hermes/bin/hermes /home/{{ hermes_user }}/bin/hermes
  ansible.builtin.file:
    src: /home/{{ hermes_user }}/.hermes/bin/hermes
    dest: /home/{{ hermes_user }}/bin/hermes
    owner: "{{ hermes_user }}"
    group: "{{ hermes_group }}"
    state: link

- name: Configure Hermes
  template:
    src: config.toml.j2
    dest: /home/{{ hermes_user }}/.hermes/config.toml

- name: Installing Hermes systemd service
  template:
    src: hermes.service.j2
    dest: /etc/systemd/system/hermes.service

- name: Start Hermes systemd service
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "hermes"

- name: Rebooting the machine
  include_role:
    name: reboot
  when: reboot | default(false) | bool