---
- name: Base
  import_tasks: base.yml
  
- name: Configure Hermes
  import_tasks: config.yml

- name: Install Hermes systemd service
  template:
    src: hermes.service.j2
    dest: /etc/systemd/system/hermes.service

- name: Start Hermes systemd service
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "hermes"

- name: Rebooting the machine
  include_role:
    name: reboot
  when: reboot | default(false) | bool
