---


- name: Remove and reinstall python3-openssl (Workaround for DO Ubuntu image)
  apt:
    state: absent
    pkg:
      - python3-openssl

- name: Upgrade the system
  apt:
    update_cache: true
    upgrade: dist
  register: apt_cache
  retries: 50
  until: apt_cache is success

- name: Install system required packages
  apt:
    pkg:
      - ntp
      - python3
      - python3-pip
      - python3-apt
      - curl
      - apt-transport-https
      - software-properties-common
      - wget
      - git
      - build-essential
      - haveged
      - python3-openssl

- name: Install basic utils
  apt:
    state: present
    pkg:
      - curl
      - htop
      - mtr-tiny

- name: Set timezone to America/Toronto
  timezone:
    name: America/Toronto
