---

name: Test Gaiad Upgrades
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gaia_version: [v6.0.41]
        upgrade_version: [v7.0.0]
    steps:
      # Get system info
      - run: ifconfig
      - run: arp -a
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"

      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ansible
        run: pip3 install ansible

      - name: Configure ansible.cfg
        run: echo "transport = local" >> ansible.cfg

      - name: Configure inventory
        run: "sed 's/root@testnet.com:/local:/g' examples/inventory-local.yml > inventory.yml"

      - name: Run playbook
        run: ansible-playbook gaia.yml -i inventory.yml --extra-vars "reboot=false gaiad_version=${{ matrix.gaia_version }} gaiad_home={{ gaiad_user_home }}/.gaia gaiad_gov_testing=true"

      - name: Check cosmovisor service
        run: systemctl status cosmovisor

      - name: Check blocks are being produced
        run: tests/test_block_production.sh 127.0.0.1 26657

      - name: Test software upgrade
        run: tests/test_software_upgrade.sh 127.0.0.1 26657 {{ matrix.upgrade_version }}

      - name: Get RAM usage while gaiad is running
        run: free -m
